# Configuration

site_name: Information Retrieval for Experimaestro
site_description: experimaestro-ir Information Retrieval module for Experimaestro
repo_url: https://github.com/bpiwowar/experimaestro-ir

# Main pages
nav:
  - Home: index.md
  - Learning to rank: letor.md
  - Neural models: neural.md
  - Experimaestro: xpm.md

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - admonition
  - pymdownx.snippets:
      base_path: .
  - toc:
      baselevel: 1

plugins:
  - experimaestro:
        path: xpm
        name: Tasks and configurations
        init:
            - xpmir.mkdocs_init
        modules:
            - Learning to rank: xpmir.letor
            - Neural: xpmir.neural

# Theme
theme:
    name: readthedocs
    highlightjs: true
