[project]
name = "experimaestro-ir"
dynamic = ["version"]

[project.scripts]
xpmir = "xpmir.__main__:main"


[tool.setuptools_scm]
write_to = "xpmir/_version.py"
fallback_version = "0.0.0-dev"

[build-system]
requires = ["setuptools", "setuptools-scm", "wheel"]  # PEP 508 specifications.

[tool.pyright]
include = ["xpmir"]
