id: monobert-small
title: "monoBERT trained on MS-Marco (debug)"
description: |
    Passage Re-ranking with BERT (Rodrigo Nogueira, Kyunghyun Cho). 2019.
    https://arxiv.org/abs/1901.04085

    This model has been trained on MsMarco v1 but only a few iterations (debug)

indexation:
    requirements: duration=2 days & cpu(mem=4G)
learner:
    validation_size: 10
    steps_per_epoch: 32
    validation_interval: 1
    batch_size: 16
    max_epochs: 4
    num_warmup_steps: 30
    warmup_min_factor: 0.1
    requirements: duration=2 days & cuda(mem=8G)
evaluation:
    requirements: duration=2 days & cuda(mem=8G)
retrieval:
    k: 20
    val_k: 20
