type: duobert
Launcher: 
    gpu: true
    tags: 
    req_duration: 6 days
    mem: 48G
Learner: 
    validation_size: 500
    steps_per_epoch: 32
    validation_interval: 32
    batch_size: 64
    max_epoch: 3200
    num_warmup_steps: 10000
    warmup_min_factor: 0.1
    lr: 3.0e-6
Retriever_mono: 
    k: 1000
    val_k: 1000
Retriever_duo:
    k: 50
    val_k: 50