type: normal
Learner: 
    validation_size: 250
    steps_per_epoch: 32
    validation_interval: 32
    batch_size: 128
    max_epoch: 8192
Retriever_mono: 
    k: 500
    val_k: 500
Retriever_duo:
    k: 30
    val_k: 30