type: duobert
Learner: 
    validation_size: 500
    steps_per_epoch: 32
    validation_interval: 32
    batch_size: 64
    max_epoch: 3200
Retriever_mono: 
    k: 1000
    val_k: 1000
Retriever_duo:
    k: 50
    val_k: 50