type: small
Launcher:
    gpu: true
    tags: 
Indexation:
    requirements: duration=2 days & cpu(mem=4G)
    training_requirements: duration=2 days & cuda(mem=24G)
Learner: 
    validation_size: 10
    steps_per_epoch: 128
    validation_interval: 1
    splade_batch_size: 96
    max_epochs: 4
    num_warmup_steps: 20
    validation_interval: 1
    early_stop: 0
    lr: 2.0e-5
    requirements: duration=2 days & cuda(mem=8G) * 2
Evaluation: 
    requirements: duration=2 days & cuda(mem=8G)
base_retriever: 
    topK: 20
tas_balance_retriever: 
    retTopK: 10
    indexspec: OPQ4_16,IVF256_HNSW32,PQ4
    faiss_max_traindocs: 15_000
full_retriever:
    batch_size_full_retriever: 20