id: duobert
title: "DuoBERT"
description: |
    DuoBERT model

        R. Nogueira, W. Yang, K. Cho, et J. Lin, « Multi-Stage Document Ranking with BERT », arXiv:1910.14424 [cs], oct. 2019. http://arxiv.org/abs/1910.14424


gpu: true
indexation:
    requirements: duration=6 days & cpu(mem=4G, cores=8)

validation_size: 500

retrieval:
    requirements: duration=2 days & cuda(mem=24G)
    k: 100
    base_k: 50

monobert:
    steps_per_epoch: 32
    validation_interval: 32
    batch_size: 64
    max_epochs: 3200
    num_warmup_steps: 10000
    warmup_min_factor: 0
    lr: 3.0e-6
    requirements: duration=4 days & cuda(mem=24G) * 2


duobert:
    steps_per_epoch: 32
    validation_interval: 32
    batch_size: 128
    max_epochs: 3200
    num_warmup_steps: 10000
    warmup_min_factor: 0
    lr: 3.0e-6
    requirements: duration=4 days & cuda(mem=24G) * 2

    base_validation_top_k: 1000
    validation_top_k: 50
