type: normal
Learner: 
    validation_size: 500
    steps_per_epoch: 32
    validation_interval: 32
    batch_size: 64
    max_epoch: 3200
    num_warmup_steps: 10000
Retriever_mono: 
    k: 1000
    val_k: 1000